### ISSUE TITLE
Can not 'make run'

### ISSUE THREAD

**Issue by steffres** [marmelab/EventDrops#277]
I'm planning to contribute to this repo since for work we would want this visualization with some adaptations. However I'm struggling with getting the node instance running (I come from back-end only so far, thus new to JS).

**What you were expecting:**

I tried to set up a running node instance to dig into the code and play with it.

**What happened instead:**

It aborted with errors at:
```
make run
```

**Steps to reproduce:**

I ran the following commands as outlined in your README:
```
git clone https://github.com/marmelab/EventDrops
cd EventDrops
make install
make run
```

wherein

```
make install
```
produced some (probably irrelevant) warnings:
```
npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

...

npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN eslint-config-airbnb-base@11.3.2 requires a peer of eslint-plugin-import@^2.7.0 but none was installed.
npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none was installed.

```

But majorly
```
make run
```
aborted with the following errors:
```
npm start

> event-drops@1.3.0 start /home/steff-vm/visualizations/EventDrops/git/test/EventDrops
> webpack-dev-server --config webpack.demo.js --colors --devtool cheap-module-inline-source-map --host=0.0.0.0

/home/steff-vm/visualizations/EventDrops/git/test/EventDrops/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/steff-vm/visualizations/EventDrops/git/test/EventDrops/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/home/steff-vm/visualizations/EventDrops/git/test/EventDrops/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! Linux 5.0.0-29-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! event-drops@1.3.0 start: `webpack-dev-server --config webpack.demo.js --colors --devtool cheap-module-inline-source-map --host=0.0.0.0`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the event-drops@1.3.0 start script 'webpack-dev-server --config webpack.demo.js --colors --devtool cheap-module-inline-source-map --host=0.0.0.0'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the event-drops package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config webpack.demo.js --colors --devtool cheap-module-inline-source-map --host=0.0.0.0
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs event-drops
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls event-drops
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/steff-vm/visualizations/EventDrops/git/test/EventDrops/npm-debug.log
Makefile:7: recipe for target 'run' failed
make: *** [run] Error 1
```
Telling from the error message I was digging into the file
```
./node_modules/webpack-cli/bin/config-yargs.js
```
where I found the offending reference on line 89 
```
describe: optionsSchema.definitions.output.properties.path.description,
```
which imports 'optionsSchema' via require from the file
```
node_modules/webpack/schemas/WebpackOptions.json
``` 
wherein on line 2114 is refered 'output', but that seems to have 'properties' missing, which is refered by the 'config-yargs.js':
```
    "output": {
      "description": "Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.",
      "anyOf": [
        {
          "$ref": "#/definitions/OutputOptions"
        }
      ]
```
Can this be a versioning problem of the needed node modules?

**Environment**

EventDrops Version: the most recent git commit on master: 7cb3818
```
$ node --version
v8.10.0
$ npm --version
3.5.2
$ uname -a
Linux base-vm 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by steffres** [comment]
Sorry, forgot the log, which is not in the subirectories mentioned by the error message, but in the root folder. Its content is:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle event-drops@1.3.0~prestart: event-drops@1.3.0
6 silly lifecycle event-drops@1.3.0~prestart: no script for prestart, continuing
7 info lifecycle event-drops@1.3.0~start: event-drops@1.3.0
8 verbose lifecycle event-drops@1.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle event-drops@1.3.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/steff-vm/visualizations/EventDrops/git/EventDrops/node_modules/.bin:/opt/scripts/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle event-drops@1.3.0~start: CWD: /home/steff-vm/visualizations/EventDrops/git/EventDrops
11 silly lifecycle event-drops@1.3.0~start: Args: [ '-c',
11 silly lifecycle   'webpack-dev-server --config webpack.demo.js --colors --devtool cheap-module-inline-source-map --host=0.0.0.0' ]
12 silly lifecycle event-drops@1.3.0~start: Returned: code: 1  signal: null
13 info lifecycle event-drops@1.3.0~start: Failed to exec start script
14 verbose stack Error: event-drops@1.3.0 start: `webpack-dev-server --config webpack.demo.js --colors --devtool cheap-module-inline-source-map --host=0.0.0.0`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid event-drops@1.3.0
16 verbose cwd /home/steff-vm/visualizations/EventDrops/git/EventDrops
17 error Linux 5.0.0-29-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error event-drops@1.3.0 start: `webpack-dev-server --config webpack.demo.js --colors --devtool cheap-module-inline-source-map --host=0.0.0.0`
22 error Exit status 1
23 error Failed at the event-drops@1.3.0 start script 'webpack-dev-server --config webpack.demo.js --colors --devtool cheap-module-inline-source-map --host=0.0.0.0'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the event-drops package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --config webpack.demo.js --colors --devtool cheap-module-inline-source-map --host=0.0.0.0
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs event-drops
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls event-drops
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Busteren** [comment]
Just tried it myself:
* Node 8.0 fails with the above log
* Node 10.0 successfully runs the command `make run` 

Seems to be dependencies. Actually had a look at updating the dependencies a bit back, but never got around to it just yet; [fork](https://github.com/Busteren/EventDrops/tree/dependency_update)

**Comment by steffres** [comment]
Hi Busteren,
sorry for my late reply, had other urgent tasks to take care in between. Anyway, I could get it running now with

- npm --version: 6.9.0
- node --version: 10.16.3

Will dig further into the running code now. Thanks for your help!
